News/Models/tintuc.cs
<<<<<<< HEAD

=======
>>>>>>> parent of bde2d44... bug
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD

namespace News.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tintuc
{

    public int id { get; set; }

    public string name { get; set; }

    public string img { get; set; }

    public string description { get; set; }

    public string link { get; set; }

    public string detail { get; set; }

    public string meta { get; set; }

    public Nullable<bool> hide { get; set; }

    public Nullable<int> position { get; set; }

    public Nullable<System.DateTime> datebegin { get; set; }

    public int id_m { get; set; }



    public virtual menu menu { get; set; }

}

=======
namespace News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tintuc
    {
        public int id { get; set; }
        public string name { get; set; }
        public string img { get; set; }
        public string description { get; set; }
        public string link { get; set; }
        public string detail { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public int id_m { get; set; }
    
        public virtual menu menu { get; set; }
    }
>>>>>>> parent of bde2d44... bug
}

News/Areas/admin/Controllers/tintucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using News.Models;
using News.FW;
using PagedList;
using PagedList.Mvc;
using Model.Models;

namespace News.Areas.admin.Controllers
{
    public class tintucsController : BaseController
    {

        // GET: admin/tintucs
        public ActionResult getPagelist(int? page)
        {
            if(page == null)
            {
                page = 1;
            }
            var v = (from t in db.tintucs
                     select t).OrderByDescending(a => a.datebegin);
            int pagesize = 10;
            int pagenumber = (page ?? 1);
            return View(v.ToPagedList(pagenumber, pagesize));
        }



        public ActionResult Index()
        {
            var tintuc = db.tintucs.Include(t => t.menu);
            return View(tintuc);
        }

        // GET: admin/tintucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tintuc tintuc = db.tintucs.Find(id);
            if (tintuc == null)
            {
                return HttpNotFound();
            }
            return View(tintuc);
        }

        // GET: admin/tintucs/Create
        public ActionResult Create()
        {
            var v = from t in db.menus
                    where t.id_m != 1
                    select t;
            ViewBag.id_m = new SelectList(v, "id_m", "name");
            return View();
        }

        // POST: admin/tintucs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "id,name,img,description,link,detail,meta,hide,position,datebegin,id_m")] tintuc tintuc, HttpPostedFileBase img)
        {
            //if (ModelState.IsValid)
            //{
            //    db.tintucs.Add(tintuc);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            //ViewBag.id_m = new SelectList(db.menus, "id_m", "name", tintuc.id_m);
            //return View(tintuc);
            try
            {
                var path = "";
                var filename = "";
                if (ModelState.IsValid)
                {
                    if (img != null)
                    {
                        //filename = Guid.NewGuid().ToString() + img.FileName;
                        filename = DateTime.Now.ToString("dd-MM-yy-hh-mm-ss-") + img.FileName;
                        path = Path.Combine(Server.MapPath("~/Content/upload/img"), filename);
                        img.SaveAs(path);
                        tintuc.img = filename; //Lưu ý
                    }
                    else
                    {
                        tintuc.img = "icon.png";
                    }
                    tintuc.datebegin = Convert.ToDateTime(DateTime.Now.ToShortDateString());
                    tintuc.meta = Support.ConvertToUnSign(tintuc.meta); //convert Tiếng Việt không dấu
                    db.tintucs.Add(tintuc);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DbEntityValidationException e)
            {
                throw e;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            ViewBag.id_m = new SelectList(db.menus, "id_m", "name", tintuc.id_m);
            return View(tintuc);
        }

        // GET: admin/tintucs/Edit/5
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tintuc tintuc = db.tintucs.Find(id);
            if (tintuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_m = new SelectList(db.menus, "id_m", "name", tintuc.id_m);
            return View(tintuc);
        }
        public tintuc getById(long id)
        {
            return db.tintucs.Where(x => x.id == id).FirstOrDefault();

        }
        // POST: admin/tintucs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "id,name,img,description,link,detail,meta,hide,position,datebegin,id_m")] tintuc tintuc, HttpPostedFileBase img)
        {
            //if (ModelState.IsValid)
            //{
            //    db.Entry(tintuc).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //ViewBag.id_m = new SelectList(db.menus, "id_m", "name", tintuc.id_m);
            //return View(tintuc);
            try
            {
                var path = "";
                var filename = "";
                tintuc temp = getById(tintuc.id);
                if (ModelState.IsValid)
                {
                    if (img != null)
                    {
                        //filename = Guid.NewGuid().ToString() + img.FileName;
                        filename = DateTime.Now.ToString("dd-MM-yy-hh-mm-ss-") + img.FileName;
                        path = Path.Combine(Server.MapPath("~/Content/upload/img"), filename);
                        img.SaveAs(path);
                        temp.img = filename; //Lưu ý
                    }
                    // temp.datebegin = Convert.ToDateTime(DateTime.Now.ToShortDateString());                   
                    temp.name = tintuc.name;
                    temp.description = tintuc.description;
                    temp.detail = tintuc.detail;
                    temp.meta = Support.ConvertToUnSign(tintuc.meta); //convert Tiếng Việt không dấu
                    temp.hide = tintuc.hide;
                    temp.position = tintuc.position;
                    db.Entry(temp).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DbEntityValidationException e)
            {
                throw e;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            ViewBag.id_m = new SelectList(db.menus, "id_m", "name", tintuc.id_m);
            return View(tintuc);
        }
        // GET: admin/tintucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tintuc tintuc = db.tintucs.Find(id);
            if (tintuc == null)
            {
                return HttpNotFound();
            }
            return View(tintuc);
        }

        // POST: admin/tintucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tintuc tintuc = db.tintucs.Find(id);
            db.tintucs.Remove(tintuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

News/Areas/admin/Views/tintucs/Create.cshtml
@model News.Models.tintuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}

@*<h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>tintuc</h4>
            <hr />
            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name)
                    @Html.ValidationMessageFor(model => model.name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.img)
                    @Html.ValidationMessageFor(model => model.img)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description)
                    @Html.ValidationMessageFor(model => model.description)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.link, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.link)
                    @Html.ValidationMessageFor(model => model.link)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.detail)
                    @Html.ValidationMessageFor(model => model.detail)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.meta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.meta)
                    @Html.ValidationMessageFor(model => model.meta)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.hide, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.hide)
                    @Html.ValidationMessageFor(model => model.hide)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.position, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.position)
                    @Html.ValidationMessageFor(model => model.position)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.datebegin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.datebegin)
                    @Html.ValidationMessageFor(model => model.datebegin)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.id_m, "id_m", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("id_m", String.Empty)
                    @Html.ValidationMessageFor(model => model.id_m)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red">
            <div class="panel-heading">
                Thêm mới Tin tức
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                @using (Html.BeginForm("Create", "tintucs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label("Tiêu đề", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Hình đại diện", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="img" id="img" accept=".jpg,.png,.gif,.jpeg,.bmp" />
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.description, new { @class = "form-control", @rows = 5 })
                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Chi tiết", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.detail)
                            @Html.ValidationMessageFor(model => model.detail, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.meta, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.meta, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.meta, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Ẩn", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">

                            @{
                                bool hide = false;
                            }
                            @Html.CheckBoxFor(model => hide)

                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Vị trí", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.position, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.position, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.id_m, "Ngành", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("id_m", String.Empty)
                            @Html.ValidationMessageFor(model => model.id_m)
                        </div>
                    </div>
                    @*<div class="form-group">
                        @Html.Label("Đường dẫn", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.link, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.link, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                    @*<div class="form-group">
                        @Html.Label("Ngày viết", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.datebegin, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.datebegin, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Lưu" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
                }
                <div>
                    @Html.ActionLink("Quay lại", "Index")
                </div>
            </div>
        </div>
    </div>
</div>
@section _Footer
{
    <script src="~/Areas/admin/Content/ckfinder/ckfinder.js"></script>
    <script src="~/Areas/admin/Content/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace("detail");
        var editor = CKEDITOR.replace("detail", { height: '600px' });
        customConfig: '/Areas/admin/Content/ckeditor/config.js';
    </script>
    <script>
        $(function () {
            $("#name").keyup(function () {
                var text = $.trim($(this).val().toLowerCase());
                var text_create;
                text_create = text.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a").replace(/\ /g, '-').replace(/đ/g, "d").replace(/đ/g, "d").replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y").replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u").replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ.+/g, "o").replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ.+/g, "e").replace(/ì|í|ị|ỉ|ĩ/g, "i");
                $('#meta').val(text_create);
            }).keyup();
        });
    </script>
}

News/Areas/admin/Views/tintucs/Edit.cshtml
@*@model News.Models.tintuc

    @{
        ViewBag.Title = "Edit";
        Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
    }

    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>tintuc</h4>
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name)
                    @Html.ValidationMessageFor(model => model.name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.img)
                    @Html.ValidationMessageFor(model => model.img)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description)
                    @Html.ValidationMessageFor(model => model.description)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.link, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.link)
                    @Html.ValidationMessageFor(model => model.link)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.detail)
                    @Html.ValidationMessageFor(model => model.detail)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.meta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.meta)
                    @Html.ValidationMessageFor(model => model.meta)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.hide, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.hide)
                    @Html.ValidationMessageFor(model => model.hide)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.position, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.position)
                    @Html.ValidationMessageFor(model => model.position)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.datebegin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.datebegin)
                    @Html.ValidationMessageFor(model => model.datebegin)
                </div>
            </div>

            @Html.HiddenFor(model => model.id_m)

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@model News.Models.tintuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red">
            <div class="panel-heading">
                Cập nhật Tin tức
            </div>
            
            <!-- /.panel-heading -->
            <div class="panel-body">

                @using (Html.BeginForm("Edit", "tintucs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    
                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.id)

                    <div class="form-group">
                        @Html.Label("Tiêu đề", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Hình đại diện", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            <input type="file" name="img" id="img" accept=".jpg,.png,.gif,.jpeg,.bmp" />
                        </div>
                        <div class="col-md-4">
                            <img src="~/Content/upload/img/@Model.img"  />
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.Label("Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.description, new { @class = "form-control", @rows = 5 })
                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.Label("Chi tiết", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.detail)
                            @Html.ValidationMessageFor(model => model.detail, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.meta, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.meta, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.meta, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Ẩn", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @{
                                bool hide = (Model.hide.GetValueOrDefault(false) ? true : false);
                            }
                            @Html.CheckBoxFor(model => hide)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Vị trí", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.position, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.position, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @Html.HiddenFor(model => model.id_m)

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Lưu" class="btn btn-danger" />
                        </div>
                    </div>
                </div>
                }

                <div>
                    @Html.ActionLink("Quay lại", "Index")
                </div>
            </div>
        </div>
    </div>
</div>
@section _Footer
{
    <script src="~/Areas/admin/Content/ckfinder/ckfinder.js"></script>
    <script src="~/Areas/admin/Content/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        var editor = CKEDITOR.replace("detail");
        var editor = CKEDITOR.replace("detail", { height: '800px' });
        customConfig: '/Areas/admin/Content/ckeditor/config.js';
    </script>
    <script>
        $(function () {
            $("#name").keyup(function () {
                var text = $.trim($(this).val().toLowerCase());
                var text_create;
                text_create = text.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a").replace(/\ /g, '-').replace(/đ/g, "d").replace(/đ/g, "d").replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y").replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u").replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ.+/g, "o").replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ.+/g, "e").replace(/ì|í|ị|ỉ|ĩ/g, "i");
                $('#meta').val(text_create);
            }).keyup();
        });
    </script>
}

News/Areas/admin/Views/tintucs/Index.cshtml
@model IEnumerable<News.Models.tintuc>
@{
    /**/

    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}

<h2>Danh sách các bài viết</h2>

<p>
    @Html.ActionLink("Tạo mới", "Create")
</p>

<div class="row">
    @Html.Action("getPagelist", "tintucs")
</div>