News/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using News.Models;
using News.FW;
using PagedList;
using PagedList.Mvc;

namespace News.Controllers
{
    public class ContactsController : Controller
    {
        private NewsEntities db = new NewsEntities();

        // GET: Contacts
        
        public ActionResult Index()
        {
            return View();
        }

        // GET: Contacts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: Contacts/Create
        public ActionResult Create()
        {
            var v = from t in db.menus
                    where t.id_m != 1
                    select t;
            ViewBag.id_m = new SelectList(v, "id_m", "name");
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_contact,name,img,description,detail,datebegin,id_m")] Contact contact, HttpPostedFileBase img)
        {
            //if (ModelState.IsValid)
            //{
            //    db.Contacts.Add(contact);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            //ViewBag.id_m = new SelectList(db.menus, "id_m", "name", contact.id_m);
            //return View(contact
            try
            {
                var path = "";
                var filename = "";
                if (ModelState.IsValid)
                {
                    if (img != null)
                    {
                        //filename = Guid.NewGuid().ToString() + img.FileName;
                        filename = DateTime.Now.ToString("dd-MM-yy-hh-mm-ss-") + img.FileName;
                        path = Path.Combine(Server.MapPath("~/Content/upload/img"), filename);
                        img.SaveAs(path);
                        contact.img = filename; //Lưu ý
                    }
                    else
                    {
                        contact.img = "icon.png";
                    };
                    db.Contacts.Add(contact);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DbEntityValidationException e)
            {
                throw e;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            ViewBag.id_m = new SelectList(db.menus, "id_m", "name", contact.id_m);
            return View(contact);
        }

        // GET: Contacts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_m = new SelectList(db.menus, "id_m", "name", contact.id_m);
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_contact,name,img,description,detail,datebegin,id_m")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_m = new SelectList(db.menus, "id_m", "name", contact.id_m);
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contact contact = db.Contacts.Find(id);
            db.Contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

News/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

News/Views/Shared/_Mylayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title - TDTU Tin tức</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link href=”~/Content/PagedList.css” rel=”stylesheet” type=”text/css” />
    <link rel="icon" type="image/png" href="~/Content/image/icon.jpg" />
    <link href="~/Areas/admin/Content/dist/css/sb-admin-2.css" rel="stylesheet">
    <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel="stylesheet" type="text/css" href="~/Content/css/temp.css">
    <!--===============================================================================================-->

    <!-- Bootstrap Core CSS -->
    <link href=”~/Content/PagedList.css” rel=”stylesheet” type=”text/css” />



    <link rel="stylesheet" type="text/css" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/fonts/fontawesome-5.0.8/css/fontawesome-all.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/css/util.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/css/main.css">
    <!--===============================================================================================-->
</head>
<body class="animsition">

    <!-- Header -->
    <header>
        <!-- Header desktop -->
        <div class="container-menu-desktop">
            <div class="topbar">
                <div class="content-topbar container h-100">
                    <div class="left-topbar">

                        <a href="@Url.Action("About", "Home")" class="left-topbar-item">
                            Giới thiệu
                        </a>
                        <a href="@Url.Action("Create", "Contacts")" class="left-topbar-item">
                            Liên hệ
                        </a>
                    </div>

                    
                </div>
            </div>

            <!-- Header Mobile -->
            <div class="wrap-header-mobile">
                <!-- Logo moblie -->
                <div class="logo-mobile">
                    <a href="@Url.Action("Index","Home")"><img src="~/Content/image/icon.jpg" alt="IMG-LOGO"></a>
                </div>

                <!-- Button show menu -->
                <div class="btn-show-menu-mobile hamburger hamburger--squeeze m-r--8">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </div>
            </div>

            <!-- Menu Mobile -->
            <div class="menu-mobile">
                <ul class="topbar-mobile">
                    

                    <li class="left-topbar">
                        <a href="@Url.Action("About","Home")" class="left-topbar-item">
                            Giới thiệu
                        </a>

                        <a href="@Url.Action("Create","Contact")" class="left-topbar-item">
                            Liên hệ
                        </a>
                    </li>

                </ul>

                <ul class="main-menu-m">
                    @{ Html.RenderAction("getMenu", "Home");}
                </ul>
            </div>

            <!--  -->
            <div class="wrap-logo no-banner container">
                <!-- Logo desktop -->
                <div class="logo">
                    <a href="@Url.Action("Index","Home")"><img src="~/Content/image/banner.jpg" alt="LOGO"></a>
                </div>
            </div>

            <!--  -->
            <div class="wrap-main-nav">
                <div class="main-nav">
                    <!-- Menu desktop -->
                    <nav class="menu-desktop">
                        <a class="logo-stick" href="@Url.Action("Index","Home")">
                            <img src="~/Content/image/icon.jpg" alt="LOGO">
                        </a>

                        <ul class="main-menu justify-content-center">
                            @{Html.RenderAction("getMenuDesktop", "Home");}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <!-- Headline -->
    <div class="container">
        <div class="bg0 flex-wr-sb-c p-rl-20 p-tb-8">
            <div class="f2-s-1 p-r-30 size-w-0 m-tb-6 flex-wr-s-c">
                <span class="text-uppercase cl2 p-r-8">
                    Tin mới nhất :
                </span>

                @{Html.RenderAction("getNewTrending", "Home");}
            </div>
            <form action=" @Url.Action("Search","Home")" method="get">
                <div class="pos-relative size-a-2 bo-1-rad-22 of-hidden bocl11 m-tb-6">
                    <input class="f1-s-1 cl6 plh9 s-full p-l-25 p-r-45" type="search" name="key" placeholder="Search" required>
                    <button class="flex-c-c size-a-1 ab-t-r fs-20 cl2 hov-cl10 trans-03" type="submit" >
                        <i class="zmdi zmdi-search"></i>
                    </button>
                </div>
            </form>
            
            
        </div>
    </div>
    <section class="bg0">
        <div class="container">
            <div class="row m-rl--1">
                @{Html.RenderAction("getNewhomepage", "Home");}
            </div>
        </div>
    </section>

    <section class="bg0 p-t-70">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10 col-lg-8">
                    <div class="p-b-20">
                        <!-- Entertainment  -->
                        <!-- Other -->
                        @RenderBody()
                        
                        <!-- Travel  -->

                    </div>
                </div>

                <div class="col-md-10 col-lg-4">
                    <div class="p-l-10 p-rl-0-sr991 p-b-20">
                        <!-- Stay Connected -->
                        <!-- Most Popular -->
                        <div class="p-b-30">
                            <div class="how2 how2-cl4 flex-s-c">
                                <h3 class="f1-m-2 cl3 tab01-title">
                                    Bài viết mới nhất
                                </h3>
                            </div>

                            @{Html.RenderAction("getNewsforlayout", "Home");}
                        </div>

                        <!--  -->
                        <!-- Video -->
                        <!-- Subscribe -->
                        <div class="bg10 p-rl-35 p-t-28 p-b-35 m-b-55" style="    height: 220px;border: outset;">
                            <h5 class="f1-m-5 cl0 p-b-10">
                                Liên hệ
                            </h5>

                            <p class="f1-s-1 cl0 p-b-25">
                                Mọi thắc mắc ,đóng góp của độc giả xin liên hệ với chúng tôi.
                            </p>
                            <form class="size-a-9 pos-relative">
                                <a href="/Home/Contact" class="size-a-10 flex-c-c ab-t-r fs-16 cl9 hov-cl10 trans-03"style="background-color: ghostwhite; width: 83px;position: unset;height: 41px;">
                                    Tại đây
                                    <i class="fa fa-arrow-right "style="margin-left: 10px;"></i>
                                </a>

                            </form>
                        </div>

                        <!-- Tag -->
                        @{Html.RenderAction("getTag", "Home");}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer>
        <div class="bg2 p-t-40 p-b-25">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 p-b-20">
                        <div class="size-h-3 flex-s-c">
                            <a href="@Url.Action("Index","Home")">
                                <img class="max-s-full" style="width:124px" src="~/Content/image/icon.jpg" alt="LOGO">
                            </a>
                        </div>

                        <div>
                            <p class="f1-s-1 cl11 p-b-16">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempor magna eget elit efficitur, at accumsan sem placerat. Nulla tellus libero, mattis nec molestie at, facilisis ut turpis. Vestibulum dolor metus, tincidunt eget odio
                            </p>

                            <p class="f1-s-1 cl11 p-b-16">
                                Any questions? Call us on (+1) 96 716 6879
                            </p>

                            <div class="p-t-15">
                                <a href="#" class="fs-18 cl11 hov-cl10 trans-03 m-r-8">
                                    <span class="fab fa-facebook-f"></span>
                                </a>
                                </a>
                            </div>
                        </div>
                    </div>

                    @{Html.RenderAction("getNewFooter", "Home");}

                    @{Html.RenderAction("getCategory", "Home");}
                </div>
            </div>
        </div>

        <div class="bg11">
            <div class="container size-h-4 flex-c-c p-tb-15">
                <span class="f1-s-1 cl0 txt-center">
                    Copyright © 2019 - Made by Cao Gia Hieu And Ha De Minh

                    <a href="#" class="f1-s-1 cl10 hov-link1"> </a>
                        
                </span>
            </div>
        </div>
    </footer>

    <!-- Back to top -->
    <div class="btn-back-to-top" id="myBtn">
        <span class="symbol-btn-back-to-top">
            <span class="fas fa-angle-up"></span>
        </span>
    </div>

    <!-- Modal Video 01-->


    <!--===============================================================================================-->
    <script src="~/Scripts/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Scripts/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Scripts/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Scripts/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Scripts/js/main.js"></script>
   
    @section _Footer
{
        <script src="~/Areas/admin/Content/ckfinder/ckfinder.js"></script>
        <script src="~/Areas/admin/Content/ckeditor/ckeditor.js"></script>
        <script type="text/javascript">
        var editor = CKEDITOR.replace("detail");
        var editor = CKEDITOR.replace("detail", { height: '600px' });
        customConfig: '/Areas/admin/Content/ckeditor/config.js';
        </script>
        <script>
        $(function () {
            $("#name").keyup(function () {
                var text = $.trim($(this).val().toLowerCase());
                var text_create;
                text_create = text.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a").replace(/\ /g, '-').replace(/đ/g, "d").replace(/đ/g, "d").replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y").replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u").replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ.+/g, "o").replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ.+/g, "e").replace(/ì|í|ị|ỉ|ĩ/g, "i");
                $('#meta').val(text_create);
            }).keyup();
        });
        </script>
    }


</body>
</html>