News/Areas/admin/Controllers/Contacts_adminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using News.Models;
using News.FW;
using PagedList;
using PagedList.Mvc;

namespace News.Areas.admin.Controllers
{
    public class Contacts_adminController : BaseController
    {
        private NewsEntities db = new NewsEntities();

        // GET: admin/Contacts_admin
        public ActionResult getPagelist(int? page)
        {
            if (page == null)
            {
                page = 1;
            }
            var v = (from t in db.Contacts
                     select t).OrderByDescending(a => a.ID_contact);
            int pagesize = 10;
            int pagenumber = (page ?? 1);
            return View(v.ToPagedList(pagenumber, pagesize));
        }
        public ActionResult Index()
        {
            var contacts = db.Contacts.Include(c => c.menu);
            return View(contacts.ToList());
        }

        // GET: admin/Contacts_admin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: admin/Contacts_admin/Create
        public ActionResult Create()
        {
            ViewBag.id_m = new SelectList(db.menus, "id_m", "name");
            return View();
        }

        // POST: admin/Contacts_admin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_contact,name,img,description,detail,datebegin,id_m")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Contacts.Add(contact);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_m = new SelectList(db.menus, "id_m", "name", contact.id_m);
            return View(contact);
        }

        // GET: admin/Contacts_admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_m = new SelectList(db.menus, "id_m", "name", contact.id_m);
            return View(contact);
        }

        // POST: admin/Contacts_admin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_contact,name,img,description,detail,datebegin,id_m")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_m = new SelectList(db.menus, "id_m", "name", contact.id_m);
            return View(contact);
        }

        // GET: admin/Contacts_admin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: admin/Contacts_admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contact contact = db.Contacts.Find(id);
            db.Contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

News/Areas/admin/Views/Contacts_admin/Create.cshtml
@model News.Models.Contact

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contact</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.img)
                @Html.ValidationMessageFor(model => model.img)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description)
                @Html.ValidationMessageFor(model => model.description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.detail)
                @Html.ValidationMessageFor(model => model.detail)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datebegin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datebegin)
                @Html.ValidationMessageFor(model => model.datebegin)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_m, "id_m", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_m", String.Empty)
                @Html.ValidationMessageFor(model => model.id_m)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

News/Areas/admin/Views/Contacts_admin/Delete.cshtml
@model News.Models.Contact

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red">
            <div class="panel-heading">
                Xóa 1liên hệ
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                <h3>Bạn muốn xóa liên hệ này?</h3>
                <div>

                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            Tiêu đề
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.name)
                        </dd>

                        <dt>
                            Hình ảnh
                        </dt>

                        <dd>
                            <img src="~/Content/upload/img/@Model.img" width="150px" />
                        </dd>

                        <dt>
                            Mô tả
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.description)
                        </dd>

                        <dt>
                            Chi tiết
                        </dt>

                        <dd>
                            @Html.Raw(Model.detail)
                        </dd>


                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Xoá" class="btn btn-danger" /> |
                            @Html.ActionLink("Quay lại", "Index")
                        </div>
                    }
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

News/Areas/admin/Views/Contacts_admin/Details.cshtml
@model News.Models.Contact

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}

<h2>Thông tin</h2>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-red">
            <div class="panel-heading">
                Chi tiết liên hệ
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>
                        Tiêu đề
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.name)
                    </dd>

                    <dt>
                        Hình ảnh
                    </dt>

                    <dd>
                        <img src="~/Content/upload/img/@Model.img" width="150px" />
                    </dd>

                    <dt>
                        Mô tả
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.description)
                    </dd>

                    <dt>
                        Chi tiết
                    </dt>

                    <dd>

                        @Html.Raw(Model.detail)
                    </dd>
                    

                </dl>

                <p>
                    @Html.ActionLink("Quay lại", "Index")
                </p>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>

News/Areas/admin/Views/Contacts_admin/Edit.cshtml
@model News.Models.Contact

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contact</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID_contact)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.img)
                @Html.ValidationMessageFor(model => model.img)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description)
                @Html.ValidationMessageFor(model => model.description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.detail)
                @Html.ValidationMessageFor(model => model.detail)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datebegin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datebegin)
                @Html.ValidationMessageFor(model => model.datebegin)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_m, "id_m", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_m", String.Empty)
                @Html.ValidationMessageFor(model => model.id_m)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

News/Areas/admin/Views/Contacts_admin/Index.cshtml
@model IEnumerable<News.Models.Contact>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_adminLayout.cshtml";
}

<h2>Liên hệ</h2>

<div class="row">
    @Html.Action("getPagelist", "Contacts_admin")
</div>

News/Areas/admin/Views/Contacts_admin/getPagelist.cshtml
@model PagedList.IPagedList<News.Models.Contact>
@using PagedList.Mvc;
<table class="table table-striped table-bordered table-hover" id="example" style="width:100%">
    <tr>
        <th>
            Tên
        </th>
        <th>
            Ảnh minh hoạ
        </th>
        <th>
            Tên bài viết
        </th>
        <th>
            Chi tiết
        </th>
        <th>
            Ngành
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                <img src="~/Content/upload/img/@item.img" width="50" class="img-thumbnail" alt="None" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @*@{
                    if (item.detail.Length >= 100)
                    {
                        @item.detail.Substring(0, 100) <text>...</text>
                    }
                    else
                    {
                        @item.detail
                    }
                    
                }*@ 
                @Html.DisplayFor(modelItem => item.detail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.menu.name)
            </td>
            <td>
                <center>
                    @Html.ActionLink(" ", "Details", new { id = item.ID_contact }, htmlAttributes: new { @class = "btn btn-info glyphicon glyphicon-unchecked" })<br />
                    @Html.ActionLink(" ", "Delete", new { id = item.ID_contact }, htmlAttributes: new { @class = "btn btn-danger glyphicon glyphicon-remove" })<br />
                </center>
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>*@
        </tr>
    }

</table>

@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page }))